### ISSUE TITLE
Whitespace between checkbox and default slot in RefinementList

### ISSUE THREAD

**Issue by NicTorgersen** [algolia/vue-instantsearch#381]
Insanely tiny bug incoming!

**What is the current behavior?**

There is an awkward whitespace between checkbox and text content. This causes a visual bug with the UI when the label has `text-decoration: underline;`.

**What is the expected behavior?**

That there's no hard coded whitespace between the checkbox and the text content.

As seen here, Filter 1 has the issue. Filter 2 has the whitespace removed, which is the expected visual style.
<img width="110" alt="screen shot 2018-01-24 at 11 19 33" src="https://user-images.githubusercontent.com/1327106/35326971-8f518282-00f8-11e8-9b99-7782ab87bff0.png">

**What is the proposed solution?**

I cloned the repo, and had a look at the component source. It looks a lot like there's a newline character which is being converted to a whitespace between the checkbox and default slot.

**What is the version you are using? Always use the latest one before opening a bug issue.**

Version 1.3.3 of vue-instantsearch

For the moment I'm using some CSS tricks to rectify the issue.

```css
.ais-refinement-list__item label { font-size: 0; } /* this does the trick */
.ais-refinement-list__item input { font-size: 16px; }
.ais-refinement-list__item span { font-size: 16px; } /* added inline template with span around content */
```
